
# Author: Haris Zafeiropoulos
# Date: May, 2025
# Description: configuration file for running FlashWeave test

# ------
# INPUT/OUTPUT
# ------

abundance_table_file: 
  file_path: input_files/testAbundMeta.tsv
  description: "Filename of the abundance table file.
  The taxonomy scheme in this case is irrelevant.
  However, you need to make sure that the sequence identifiers used in this table, are the same
  with those in your network (if one provided) as well as with those in your bins/faa/xml files, again if such provdied."
  required: true
  examples: 
    - thirty_Samples.tsv
    - counts_genomes_taxonomies.tsv
  type: string


output_directory: 
  dir_path: output_files
  description: Name of the output folder that will be built inside the io_path directory.
  required: true
  type: string


# -----
# Computing
# -----
threads:
  value: 2
  description: "Number of CPUs to be used."
  type: integer

# -----
# Seed complementarity
# -----
seed_complementarity:
  value: false
  description: This is the most time-consuming and challengint step of the workflow. You may perform microbetag with or without it by setting \
                this argument as true or false correspondinly.
  required: true
  type: bool

# -----
# Pathway complementarity: if the pathway_complementarity parameter is set as false, the rest of the parameters will not be considered. 
# -----
pathway_complementarity:
  value: false
  description: "Set whether pathway complementarities should be calcuated and then used to annotated the edges of the co-occurrence network."
  required: true
  type: bool


# -----
# Flashweave
# -----
metadata_file:
  file_path: input_files/metadata.tsv
  description: 
  type:
  required: false


flashweave_args:
    heterogeneous:
      value: False
      description: >
        Enable heterogeneous mode for multi-habitat or -protocol data with at least thousands of samples (FlashWeaveHE).
      required: true
      default: false
      type: bool
    
    sensitive:
      value: True
      description: >
        Enable fine-grained associations (FlashWeave-S, FlashWeaveHE-S), sensitive=false results in the fast modes 
        FlashWeave-F or FlashWeaveHE-F.
      required: true
      default: true
      type: bool

    max_k:
      value:
      description: >
        Maximum size of conditioning sets, high values can strongly increase runtime. 
        max_k=0 results in no conditioning (univariate mode).
      required: false
      default: 3
      type: integer

    n_obs_min:
      value: 10
      desription: >
        Don't compute associations between variables having less reliable samples (i.e. non-zero if heterogeneous=True) 
        than this number. 
        -1  automatically choose a threshold.
      required: false
      default: 20 (in case of discrete computer systems)
      type: integer

    alpha:
      value:
      description: Threshold used to determine statistical significance.
      required: false
      default: 0.01
      type: 

    conv:
      value:
      description: >
        Convergence threshold, i.e. if conv=0.01 assume convergence if the number of edges increased by only 1% after 100% 
        more runtime (checked in intervals).
      required: false
      default: 0.01
      type: 

    feed_forward:
      value:
      description: Enable feed-forward heuristic
      required: false
      default: true
      type: boolean

    max_tests: 
      value:
      description: >
        Maximum number of conditional tests that should be performed on a variable pair before association is assumed.
      required: false
      default: 10e6
      type: integer

    hps:
      value:
      description: Reliability criterion for statistical tests when sensitive=false.
      required: false
      default: 5
      type: integer

    FDR:
      value: 
      description: >
        Perform False Discovery Rate correction (Benjamini-Hochberg method) on pairwise associations.
      required: false
      default: true
      type: boolean

    time_limit:
      value: 
      description: >
        If feed-forward heuristic is active, time_limit determines the interval (seconds) at which neighborhood information 
        is updated.
        -1.0 set heuristically, 0.0 no time_limit, otherwise time limit in seconds
      required: false
      default: -1.0
      type: float

    normalize:
      value: 
      description: Automatically choose and perform data normalization (based on sensitive and heterogeneous)
      required: false
      default: true
      type: bool

    track_rejections:
      value: 
      description: >
        Store for each discarded edge, which variable set lead to its exclusion (can be memory intense for large networks)
      required: false
      default: false
      type: boolean

    verbose:
      value:
      description: Print progress information
      required: false
      default: true
      type: bool
