# Provide the filename of your OTU table
otu_table: string 

# In case silva_db is False, the user needs to have an extra column 
# on the OTU table with the NCBI taxonomy id of the species found.
# Assignmnets that are not at the species level should filled with "null".
silva_db: boolean 


silva_version: [128, 132]  # Not sure yet if needed

# 
otu_identifier_column: string    # e.g. #OTU

taxonomy_column_name: string     # e.g. "Classification"

