# microbetag: annotating microbial co-occurrence networks
# 
# Aim:   this Docker image will encapsulate all the related  
#        tools, databases and software modules for the microbetag
#        network annotator
# 
# Usage: docker build -t hariszaf/microbetag_base:<tag> .

FROM ubuntu:20.04

# On Ubuntu 20.04 (Focal Fossa):
#     The default python3 version in the official repos is Python 3.8.10.

LABEL maintainer = "Haris Zafeiropoulos" 
LABEL contact    = "haris.zafeiropoulos@kuleuven.be"
LABEL build_date = "2025-02"
LABEL version    = "v1.0.0"

# This mode allows zero interaction while installing or upgrading the system via apt; 
# it accepts the default answer for all questions.
ENV DEBIAN_FRONTEND noninteractive
WORKDIR /home

# Get general software; bzip is required to install R 
RUN apt-get update &&\
    apt-get install -y software-properties-common &&\
    apt-get update --fix-missing && \
    apt-get install -y wget && \
    apt-get install -y git && \
    apt-get install -y unzip && \
    apt-get install -y mlocate && \
    apt-get install -y libbz2-dev && \
    apt-get clean &&\
    rm -rf /var/lib/apt/lists/*

# Set Python
# Install py39 from deadsnakes repository
# Install pip from standard ubuntu packages
RUN add-apt-repository ppa:deadsnakes/ppa &&\
    apt-get install -y python3 &&\
    apt-get install -y python3-pip

# Install some extra staff and leave out later what is not needed
RUN apt-get install -y liblzma-dev \
    libcurl4-openssl-dev \
    libglib2.0-0 \
    libxext6 \
    libsm6 \
    libxrender1 \
    mercurial \
    subversion \
    autoconf \
    autogen \
    libtool \
    zlib1g-dev

# Based on the .devcontainer/setup_codespace.sh script of the kul2025 branch of the metabolic_toy_model repo 
RUN apt-get update &&\ 
    apt install -y vim &&\
    apt-get install patchelf  # Required for Julia..

# Install Miniconda
# -----
ENV MINICONDA_DIR="$HOME/miniconda"
ENV CONDA_BIN="$MINICONDA_DIR/bin/conda"

RUN echo "Installing Miniconda..." &&\
    wget -q https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O /tmp/miniconda.sh &&\
    bash /tmp/miniconda.sh -b -p "$MINICONDA_DIR" &&\
    rm /tmp/miniconda.sh

# --- Make conda available in the current script ---
ENV PATH="${MINICONDA_DIR}/bin:${PATH}"
RUN eval "$($CONDA_BIN shell.bash hook)"


# -----------------------------
# System dependencies (for pip builds)
# -----------------------------
RUN apt-get update && apt-get install -y \
    build-essential \
    ca-certificates \
    curl \
    git \
    && update-ca-certificates

# -----------------------------
# Accept TOS and upgrade pip in base
# -----------------------------
RUN eval "$($MINICONDA_DIR/bin/conda shell.bash hook)" && \
    $MINICONDA_DIR/bin/conda tos accept --override-channels --channel https://repo.anaconda.com/pkgs/main && \
    $MINICONDA_DIR/bin/conda tos accept --override-channels --channel https://repo.anaconda.com/pkgs/r && \
    $MINICONDA_DIR/bin/conda install -n base python=3.10 pip setuptools wheel -y && \
    $MINICONDA_DIR/bin/conda run -n base pip install --upgrade pip setuptools wheel

# Update patchelf
RUN apt-get update && apt-get install -y patchelf

# Get microbetag
WORKDIR /microbetag
ADD . ./
RUN bash setup_environment.sh 

